name: Publish Gem

on:
  push:
    branches: [ main ]
    tags: [ v* ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish to Rubygems
        uses: cadwallion/publish-rubygems-action@v1.0.0
